name: Vercel Production Deployment

on:
  push:
    branches:
      - main  

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Ensure you're using a compatible Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      - name: Install Vercel CLI
        run: npm install --global vercel

      - name: Deploy to Vercel
        run: |
          vercel --token=${{ secrets.VERCEL_TOKEN }} --prod --confirm
